### ISSUE TITLE
Refactoring block #1

### ISSUE THREAD

**Issue by jankapunkt** [openqda/openqda#43]
Although we should implement refactoring as a constant part of our dev process, we started off with a rather rapid prototyping and left things a bit unmanaged due to the fast paced development cycles. Therefore we should introduce constant refactoring with an initial refactoring sprint.

Estimated effort: 1 week, two devs

## Objectives

- clear abstractions and APIs to maximize extensibility
- decent test coverage to detect regressions early and precise
- understandable class/function/variable naming
- detect context boundaries and restructure towards them
- prepare for plugin architecture 

## Resources

- refactoring book: https://www.oreilly.com/library/view/refactoring-improving-the/9780134757681/
- catalog of refactoring pattern: https://refactoring.com/catalog/
- architecture pattern: https://www.oreilly.com/library/view/software-architecture-patterns/9781491971437/
- clean code: https://www.oreilly.com/library/view/clean-architecture-a/9780134494272/
- domain driven design: https://www.oreilly.com/library/view/domain-driven-design-tackling/0321125215/
- TODO: add Vue.js (@jankapunkt) and Laravel-specific (@alessandrobelli) refactoring resources here

We can access the books via our Uni VPN

## Tasks

> Note: This is an outline / high level view of the tasks. Each task should be implemented by a pull request. Let's try to avoid big 
> (and unreviewable) pull requests by implementing multiple tasks in one PR (leading to 50+ files to review :hot_face:)

### Backend @alessandrobelli 

- [ ] ....

### Frontend @alessandrobelli 

- [ ] restructure / rename Files and folders
- [ ] Extract common code into reusable components and HOCs
- [ ] Make components testable / add unit tests
- [ ] extract Visualization plugins into own NPM packages
- [ ] Add component documentations
- [ ] Add storybook to the project to prepare transition to new design system
- [ ] Prepare tailwind classes and components for light/dark theme switching

**Comment by alessandrobelli** [comment]
I included the part for the backend, and replaced my name with yours for the frontend... that should be it, right? 😄
